feat(ratings): add option to sync stash ratings to plex media items
Darklyter/StashPlexAgent.bundle pull request #21
Opened 2023-02-14 04:32 UTC by electblake

In an effort to keep my ratings save in my stashdb, I setup stash > plex rating sync

- stash ratings get saved as user ratings in plex on metadata refresh
- stash ratings become plex stars
- uses plex api `/:/rating` endpoint (plex scene update `userRatings` did not work)
- uses `PLEXTOKEN` set in env var

2023-02-14 04:33 UTC, electblake commented on Contents/Code/__init__.py
> +        id_query = "query{findScene(id:%s){path,id,title,details,url,date,rating,rating100,paths{screenshot,stream}movies{movie{id,name}}studio{id,name,image_path,parent_studio{id,name,details}}organ
when using the stash api, I read that `ratings` is deprecated and should use rating100

2023-02-14 04:34 UTC, electblake commented on Contents/Code/__init__.py
> +                metadata.rating = stashRating
fixes issue where plex critic rating (ie. 100% for 5 stars) would be.. way too large, like 1600%

now, 4 stars = 80%

2023-02-14 17:55 UTC, electblake commented on Contents/Code/__init__.py
> +                metadata.rating = stashRating
this addresses issue #23

2023-02-18 13:59 UTC, MikeLund requested changes
Nice changes, please review comments and thanks for your contributions :)

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
> +        id_query = "query{findScene(id:%s){path,id,title,details,url,date,rating,rating100,paths{screenshot,stream}movies{movie{id,name}}studio{id,name,image_path,parent_studio{id,name,details}}organ
Remove `rating` entirely here.

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
>              if not data["rating"] is None:
Use `rating100`

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
>                      if int(data["rating"]) > 0:
Change `rating100` etc.

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
> +                metadata.rating = stashRating
Nice catch 👍

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
> +                        token = os.environ['PLEXTOKEN']
Does Plex's agent methods automatically provide this envvar in some sort of way? Or must the user make sure they have set it in their env manually? If manual changes needed, it'd be good to have a check here and maybe even include it in the preferences file for ease-of-use.

It's also unlikely people have changed the port of their PMS, but something there to consider as well.

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
> +                        if float(userRating) != float(stashRating):
Have you double-checked if Plex fully supports this numbering system? As in, `userRating` gets saved as a float/10 (so 3 stars saved as `userRating="6.0"` when using Plex's UI), but if user for example uses a different "Rating Star Precision" other than Full in Stash (or even they use Decimal rating system), I worry something might go wrong here.

I did some quick tests submitting to `pms/:/rate?identifier=com.plexapp.plugins.library&key=videoid&rating=6.9&X-Plex-Token=...` and it saved as such in the video's metadata, but it could be possible that some players suck and would malfunction if not making sure the values are always `2.0`, `4.0`, `6.0`, `8.0`, `10.0`, but maybe overly paranoid here, so probably okay.

2023-02-18 13:59 UTC, MikeLund commented on Contents/Code/__init__.py
> +                            Log("User rating %s already set to %s" % (userRating, stashRating))
I'd think these should be as DEBUG. (Might be a good code cleanup to have a `def DebugLog` or such?)

2023-02-23 16:43 UTC, electblake commented on Contents/Code/__init__.py
> +                        token = os.environ['PLEXTOKEN']
yes, it's automatically included - I only added reading from ENV, plex sets it for agents automatically

2023-02-23 16:45 UTC, electblake commented on Contents/Code/__init__.py
> +                        if float(userRating) != float(stashRating):
hrrm... I'm pretty sure plex has half-star ratings built in (I know you can set via PMS Web)

maybe I'll round it to the near whole or half-star rating ?

2023-02-23 16:46 UTC, electblake commented on Contents/Code/__init__.py
> +                            Log("User rating %s already set to %s" % (userRating, stashRating))
I'll wrap any information Log conditional DEBUG - and yeah, a wrapped `DebugLog()` sounds good to me

2023-02-24 15:49 UTC, MikeLund commented on Contents/Code/__init__.py
> +                        if float(userRating) != float(stashRating):
I personally can only click on whole stars in Plex Web for some reason, but sounds good, probably wouldn't be a problem anyways.

2023-02-26 23:04 UTC, Darklyter commented on Contents/Code/__init__.py
> +                metadata.rating = stashRating
Sorry to take so long to see your changes, but this will drop support for older versions of Stash since they used a 1-5 rating I believe.

2023-02-26 23:05 UTC, Darklyter commented on Contents/Code/__init__.py
>              if not data["rating"] is None:
That blocks compatibility with older versions of Stash

2023-02-26 23:08 UTC, merged